services:
  - name: insightloop
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
        PYTHONPATH=/opt/render/project/src 
        daphne insightloop.asgi:application --bind 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src