services:
  - name: insightloop
    type: web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic
    startCommand: |
      cd insightloop &&
      daphne insightloop.asgi:application --port $PORT --bind 0.0.0.0
    envVars:
      - key: DISABLE_COLLECTSTATIC
        value: 0
      - key: RENDER_EXTERNAL_HOSTNAME
        value: ${RENDER_EXTERNAL_HOSTNAME}
      - key: PYTHONPATH
        value: /opt/render/project/src