services:
  - name: insightloop
    type: web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      echo "=== Project Structure ==="
      find . -type d
      echo "=== Python Path ==="
      python -c "import sys; print('\n'.join(sys.path))"
      # Optional: Run collectstatic if using static files
      python manage.py collectstatic --noinput || echo "No static files to collect"
    startCommand: >
      gunicorn insightloop.asgi:application 
      --chdir insightloop 
      --worker-class uvicorn.workers.UvicornWorker 
      --bind 0.0.0.0:$PORT