services:
  - name: insightloop
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: daphne -b 0.0.0.0 -p $PORT insightloop.asgi:application
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: REDIS_URL
        fromService:
          name: insightloop-redis
          type: redis
          property: connectionString

  - name: insightloop-redis
    type: redis
    plan: free
    maxmemoryPolicy: noeviction