services:
  - name: insightloop
    type: web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python insightloop/manage.py collectstatic --no-input
    startCommand: |
      cd insightloop && daphne -b 0.0.0.0 -p $PORT insightloop.asgi:application
    envVars:
      - key: DISABLE_COLLECTSTATIC
        value: 0
      - key: RENDER_EXTERNAL_HOSTNAME
        value: ${RENDER_EXTERNAL_HOSTNAME}
      - key: PYTHONPATH
        value: /opt/render/project/src