services:
  - name: insightloop
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn insightloop.asgi:application --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: REDIS_URL
        fromService:
          name: insightloop-redis
          type: redis
          property: connectionString

  - name: insightloop-redis
    type: redis
    plan: free
    maxmemoryPolicy: noeviction