services:
  - name: insightloop
    type: web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput || echo "No static files to collect"
    startCommand: daphne insightloop.insightloop.asgi:application --port $PORT --bind 0.0.0.0