services:
  - name: insightloop
    type: web
    env: python
    buildCommand: python -m venv .venv
                  source .venv/bin/activate
                  pip install -r requirements.txt
    startCommand: >
      echo "Current directory: $(pwd)" &&
      echo "Directory contents: $(ls -l)" &&
      echo "Python path: $PYTHONPATH" &&
      PYTHONPATH=/opt/render/project/src 
      daphne insightloop.asgi:application --bind 0.0.0.0 --port $PORT
    envVars:
            - key: PYTHONPATH
              value: /opt/render/project/src/app